version: '3'
services:
  web:
    build: 
      context: ..
      dockerfile: odoo-14.0/Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ../conf:/etc/odoo
    command: python3 /opt/odoo/odoo-server -c /etc/odoo/config.conf
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-db-data: